# automatically generated by g-sorcery
# please do not edit this file

EAPI=6

REPO_URI="https://pypi.python.org/packages/cb/dd/5e58cf3c1413d2e316827e719ccf97a9d1fb738f57e73d647c7d7f130655/"
SOURCEFILE="${P}.tar.gz"
PYTHON_COMPAT=( python{2_7,3_3,3_4,3_5} )

inherit gs-pypi

DESCRIPTION="GPU-based statistical functions"

HOMEPAGE="https://github.com/wookayin/gpustat"
LICENSE="MIT"

SLOT="0"
KEYWORDS="~amd64 ~x86"

