# Copyright 1999-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

DISTUTILS_USE_PEP517=setuptools
REPO_URI="https://files.pythonhosted.org/packages/b4/69/d8c849715171aeabd61af7da080fdc60948b5a396d2422f1f4672e43d008/"
SOURCEFILE="${P}.tar.gz"
PYTHON_COMPAT=( python3_{11..13} )

inherit gs-pypi

DESCRIPTION="GPU-based statistical functions"

HOMEPAGE="https://github.com/wookayin/gpustat"
LICENSE="MIT"

SLOT="0"
KEYWORDS="~amd64 ~x86"

RDEPEND="dev-python/blessings
         dev-python/nvidia-ml-py3"
